name = "BivMatFun"
uuid = "8af482f7-afad-4070-b0c6-0cc497ebf6c5"
authors = ["Leonardo Robol <leo@robol.it>", "Stefano Massei <s.massei@tue.nl>"]
version = "0.1.0"

[deps]
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
